---
title: "Technical Interviews"
toc: true
---

<!-- # **For Profit** 💰: Technical Interviews -->

Technical Interviews are a common part of the hiring process for software engineers. They are used to assess a candidate's technical knowledge, problem-solving skills, and ability to work under pressure. Many companies use multiple rounds of technical interviews to evaluate candidates, and the questions asked can cover a wide range of topics, including data structures, algorithms, and system design.

The hiring process at a typical tech company might include a phone screen, a coding challenge, and multiple rounds of technical interviews. The technical interviews are usually conducted by engineers at the company, and they can be conducted in person or remotely. During the interview, the candidate is asked to solve coding problems on a whiteboard or a computer, and they are expected to explain their thought process as they work through the problem.


<center>

<iframe width="560" height="315" src="https://www.youtube.com/embed/1t1_a1BZ04o?si=U-JRnyz2buy1HQqC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

</center>

Technical interviews are generally <u><b>about an hour long</b></u> and involve solving one or two coding problems. At the end of the interview, the candidate is usually given the opportunity to ask questions about the company or the role.


Most technical interviews focus on problem-solving skills and algorithmic thinking. Candidates are expected to be able to write clean, efficient code and to explain their solutions clearly. In addition to coding problems, technical interviews may also include questions about system design, object-oriented design, and other technical topics.

The following video shows a mock technical interview that you can watch to get a sense of what to expect in a technical interview: 

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/1qw5ITr3k9E?si=Kwdpr1lhZnTR0fVm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</center>

## LeetCode

[LeetCode](https://leetcode.com/) is a popular platform for practicing coding interview questions, and many candidates use it to prepare for technical interviews. The problems on LeetCode cover a wide range of topics and difficulty levels, making it a valuable resource for interview preparation.

**LeetCode premium** allows simulating interviews with questions from specific companies like Google, Facebook, Amazon, and Microsoft. It also provides video solutions and additional features to help you prepare for technical interviews.

## Neetcode

The incredible breadth of problems on LeetCode can be overwhelming for beginners. You might want to consider starting with a smaller curated list of 75 problems called the “Blind 75”. This is a very popular tech insider shortlist of commonly asked interview questions. The best place to start with Blind 75, in my opinion, is NeetCode. The roadmap on the website is a great way to sequentially work through categories of problems. Moreover, each problem has an accompanying youtube video that does a great job at explaining the problem and the solution.

Competitive Programming: If you enjoyed the competitive programming aspect of the course, I would first recommend marking your calendar with The Thirty-First Annual CCSE: Southeastern Programming Contest is scheduled for 10 a.m.-1 p.m. on Saturday, November 2, 2024 in Riley Hall at Furman University. I honestly believe that we can beat Bob Jones and win the competition this year! The problems from past years are here. You should continue practicing these on your own with a stopwatch running (optionally with the Eye of the Tiger playing in the background). 

## Hiring Process

Hiring process at FAANG (Facebook, Amazon, Apple, Netflix, Google) companies is explained [here](https://www.stratascratch.com/blog/hiring-in-faang-companies-and-knowing-when-you-re-ready/) and Interviewing.io has a [blog](https://blog.interviewing.io/) that provides insights into the technical interview process. For instance, [this link](https://interviewing.io/guides/hiring-process/) gives a pretty good overview of the hiring process at big tech companies. The processes are also broken down by company, for example, [Google](https://interviewing.io/guides/hiring-process/google).


<!-- 1. TOC 
{:toc}




## Prefix Sum

	Find the Highest Altitude
	Solution
	Easy

	Find Pivot Index
	Solution
	Easy




## Bit Manipulation

	Counting Bits
	Solution
	Easy

	Single Number
	Solution
	Easy

	Minimum Flips to Make a OR b Equal to c
	Solution
	Medium

## Trie

	Implement Trie (Prefix Tree)
	Solution
	Medium

	Search Suggestions System
	Solution
	Medium

## Intervals

	Non-overlapping Intervals
	Solution
	Medium

	Minimum Number of Arrows to Burst Balloons
	Solution
	Medium -->